on:
  push:
    branches:
      - master

jobs:
  test-ossutil-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        node: [10]
    name: Test ossutil action
    steps:
      - name: Fetch repository
        uses: actions/checkout@master

      - name: Download files
        id: ossutil
        uses: go-choppy/ossutil-github-action-js@master
        with:
          ossArgs: 'cp oss://nordata-cdn/choppy/about-us.md ./'
          accessKey: ${{ secrets.ALIYUN_ACCESS_KEY }}
          accessSecret: ${{ secrets.ALIYUN_ACCESS_SECRET }}
          endpoint: oss-cn-shanghai.aliyuncs.com

      - name: Output command
        run: echo "${{steps.ossutil.outputs.command}}"
